version: '3'

services:

  ci-tools:
    build:
      context: .
      args:
        CI_TOOLS_IMAGE_VERSION: ${VERSION}
    image: ${DOCKER_REGISTRY:-localhost:5000}/codingmatters/ci-tools:${VERSION}

